# Generated by Django 3.1.7 on 2021-04-05 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parente', to='store.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(blank=True, default=False, null=True)),
                ('etat', models.CharField(choices=[('I', 'incomplete'), ('C', 'complete'), ('V', 'verifié')], default='I', max_length=1)),
                ('modification', models.BooleanField(default=False)),
                ('date_modi', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='infos_liv',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, null=True)),
                ('ref', models.CharField(max_length=40, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('marque', models.CharField(max_length=30, null=True)),
                ('promotion', models.BooleanField(default=False)),
                ('prix', models.DecimalField(decimal_places=3, max_digits=5)),
                ('prix_promo', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='store.categorie')),
                ('tva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='store.tva')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField(default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignecmds', to='store.commande')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignecmds', to='store.produit')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='store.client'),
        ),
    ]
