# Generated by Django 3.1.7 on 2021-04-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210405_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='marque',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_promo',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='ref',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='tva',
            name='taux',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
