# Generated by Django 3.1.7 on 2021-04-05 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210405_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='infos_liv',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='store.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_promo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
