# Generated by Django 3.1.7 on 2021-04-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210405_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='marque',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='ref',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
