# Generated by Django 3.1.7 on 2021-04-05 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210405_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecmd',
            name='qte',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
