# Generated by Django 3.1.7 on 2021-04-09 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210405_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=4000, null=True)),
                ('emetteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emett', to='store.client')),
                ('recepteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recep', to='store.client')),
            ],
        ),
        migrations.CreateModel(
            name='ContactVisiteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('prenom', models.CharField(blank=True, max_length=30, null=True)),
                ('tel', models.CharField(blank=True, max_length=8, null=True)),
                ('sujet', models.CharField(blank=True, max_length=40, null=True)),
                ('message', models.CharField(blank=True, max_length=4000, null=True)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.contact')),
            ],
        ),
    ]
