# Generated by Django 3.1.7 on 2021-04-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_contact_contactvisiteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='infos_liv',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='commenter',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
