# Generated by Django 3.1.7 on 2021-04-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210410_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_modi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='etat',
            field=models.CharField(choices=[('N', 'Nouveau'), ('E', 'En attente'), ('V', 'Verifié')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='produit',
            name='tva',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.DeleteModel(
            name='Tva',
        ),
    ]
