# Generated by Django 3.1.7 on 2021-04-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210410_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='totalHT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='totaltTTC',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
