# Generated by Django 3.1.7 on 2021-04-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210410_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='etat',
            field=models.CharField(choices=[('N', 'Nouveau'), ('E', 'En attente'), ('V', 'Verifié')], default='N', max_length=1),
        ),
    ]
