# Generated by Django 3.1.7 on 2021-04-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_produit_date_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='commenter',
            new_name='commentaire',
        ),
    ]
