# Generated by Django 3.1.7 on 2021-04-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20210414_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactvisiteur',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contactvisiteur',
            name='sujet',
        ),
        migrations.AddField(
            model_name='contact',
            name='sujet',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
